// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func TextChat() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"border-[1px] border-chatopia-3 rounded-md max-w-3xl mx-auto\"><h1 class=\"p-2 text-lg font-bold text-chatopia-5 border-b-[1px] border-chatopia-3\">CHAT</h1><div class=\"flex-grow flex flex-col p-2 my-2 overflow-y-scroll h-[40vh] scrollbar-chatopia\"><div id=\"chat_bubbles\" class=\"flex flex-col gap-1 pb-1\"></div><div id=\"chat_typing\"></div></div><form id=\"chat_form\" class=\"flex items-center h-14 p-1 border-chatopia-3 border-t-[1px] overflow-hidden\"><textarea id=\"chat_message\" name=\"chat_message\" rows=\"1\" class=\"rounded-md text-chatopia-2 px-2 py-3 h-full min-h-0 flex-grow resize-none leading-none focus:outline-none\" maxlength=\"200\" ws-send hx-vals='{\"message_type\":\"typing\"}' hx-trigger=\"keyup changed throttle:3s\" placeholder=\"Type a message...\"></textarea> <button id=\"send_chat_button\" type=\"button\" class=\"px-2 rounded-md h-full flex items-center justify-center\"><svg class=\"w-5 h-5 fill-chatopia-1 drop-shadow-[0_0_3px_black]\"><use href=\"/assets/icons.svg#paper-plane\"></use></svg></button></form></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
