// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func VideoChat() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<script>\n\t</script><div class=\"flex justify-center sm:flex-col gap-2\"><div class=\"relative\"><video id=\"remote_video\" class=\"h-36 w-36 sm:h-80 sm:w-80 border-2 rounded-md border-chatopia-3\" autoplay style=\"object-fit: cover; background-image: url('/assets/video_placeholder.gif'); background-size: cover; background-position: center; background-repeat: no-repeat;\"></video><div id=\"remote_video_ctrl\" class=\"absolute bottom-2 m:bottom-8 left-2 m:left-8 flex gap-2 mt-1 justify-center\"><button id=\"remote_mute_button\" onclick=\"toggleMuteRemote()\" class=\"flex items-center justify-center w-8 h-8\"><svg class=\"w-5 h-5 fill-white\"><use href=\"/assets/icons.svg#muted\"></use></svg></button></div></div><div class=\"relative\"><video id=\"local_video\" class=\"h-36 w-36 sm:h-80 sm:w-80 border-2 rounded-md border-chatopia-3\" autoplay muted style=\"object-fit: cover;\"></video><div id=\"local_video_ctrl\" class=\"absolute bottom-2 m:bottom-8 left-1/2 -translate-x-1/2 flex gap-2 mt-1 justify-center\"><button id=\"mute_button\" onclick=\"toggleMute()\" class=\"flex items-center justify-center w-8 h-8\"><svg class=\"w-5 h-5 fill-white\"><use href=\"/assets/icons.svg#mic-on\"></use></svg></button> <button id=\"camera_button\" onclick=\"toggleCamera()\" class=\"flex items-center justify-center w-8 h-8\"><svg class=\"w-5 h-5 fill-white\"><use href=\"/assets/icons.svg#cam-on\"></use></svg></button></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
